filter:
    paths: [src/*]

before_commands:
    - 'composer install --dev'

tools:
    external_code_coverage: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
    php_cs_fixer:
        enabled: true
        config: { level: psr2 }
    php_cpd:
        enabled: true
    php_analyzer:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2