sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer install --no-interaction --prefer-dist

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - rm -v ./vendor/autoload.php ./vendor/composer/!(installed.json)
